name: final-project
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - pytorch-lightning=1.1.8
  - cudatoolkit
  - pillow
  - tensorboard
  - pyyaml
  - pip:
      - pytorch-lightning-bolts
