name: final-project
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - pytorch-lightning=1.1
  - cudatoolkit
  - pandas
  - pillow
  - tensorboard
  - pyyaml
  - jupyterlab=3
  - matplotlib
  - streamlit
  - scikit-learn
  - rope
  - flake8
  - black
  - kaggle
  - pip:
      - lightning-bolts
